USE `MiniBooking` ;


insert into LOCATION (LocationID, Country, State, City, Zipcode) values (1, 'Philippines', null, 'Dangcalan', '4715');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (2, 'Japan', null, 'Ōhara', '299-4624');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (3, 'Portugal', 'Porto', 'Paços de Ferreira', '4590-170');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (4, 'China', null, 'Qiandong', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (5, 'Iran', null, 'Eslāmābād', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (6, 'Gambia', null, 'Dankunku', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (7, 'Brazil', null, 'Bebedouro', '14700-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (8, 'Indonesia', null, 'Tebluru', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (9, 'China', null, 'Guazhou', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (10, 'Poland', null, 'Suraż', '18-105');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (11, 'France', 'Aquitaine', 'Bordeaux', '33090 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (12, 'Brazil', null, 'Itaitinga', '61880-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (13, 'China', null, 'Timeng', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (14, 'Indonesia', null, 'Ciengang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (15, 'Greece', null, 'Mandráki', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (16, 'Iran', null, 'Zahedan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (17, 'Russia', null, 'Chaykovskaya', '617010');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (18, 'Sweden', 'Värmland', 'Kristinehamn', '681 22');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (19, 'Sweden', 'Västra Götaland', 'Falköping', '521 96');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (20, 'Brazil', null, 'Santa Fé do Sul', '15775-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (21, 'Russia', null, 'Novocherkassk', '346408');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (22, 'Czech Republic', null, 'Lukavice', '789 01');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (23, 'Bangladesh', null, 'Cox’s Bāzār', '6510');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (24, 'China', null, 'Jiangzao', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (25, 'Indonesia', null, 'Jaga', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (26, 'Ethiopia', null, 'Tippi', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (27, 'Indonesia', null, 'Krajan Karanganyar', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (28, 'Philippines', null, 'Cortes', '6341');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (29, 'Serbia', null, 'Sombor', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (30, 'Uganda', null, 'Buikwe', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (31, 'Philippines', null, 'Buenavista', '8601');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (32, 'Indonesia', null, 'Kemiri', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (33, 'Nigeria', null, 'Kiyawa', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (34, 'Indonesia', null, 'Balekambang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (35, 'Russia', null, 'Nekrasovka', '140074');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (36, 'Albania', null, 'Iballë', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (37, 'China', null, 'Yangfang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (38, 'Indonesia', null, 'Kebonsari', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (39, 'Philippines', null, 'Canturay', '1676');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (40, 'China', null, 'Tielu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (41, 'Mongolia', null, 'Jargalant', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (42, 'Ethiopia', null, 'Shambu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (43, 'Laos', null, 'Viengxay', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (44, 'China', null, 'Hanghuadian', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (45, 'Myanmar', null, 'Pyinmana', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (46, 'Poland', null, 'Osieczany', '32-432');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (47, 'Indonesia', null, 'Kuniran', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (48, 'Slovenia', null, 'Železniki', '4228');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (49, 'Mexico', 'Coahuila De Zaragoza', 'Francisco Villa', '26030');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (50, 'Serbia', null, 'Belgrade', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (51, 'South Africa', null, 'Flagstaff', '4821');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (52, 'Palestinian Territory', null, 'Jaba‘', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (53, 'Argentina', null, 'Jardín América', '3332');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (54, 'Kazakhstan', null, 'Aksu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (55, 'France', 'Île-de-France', 'Meaux', '77104 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (56, 'Dominican Republic', null, 'Bánica', '10802');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (57, 'Belarus', null, 'Lyeskawka', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (58, 'Philippines', null, 'Binguang', '5400');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (59, 'Indonesia', null, 'Lolak', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (60, 'Ecuador', null, 'Loja', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (61, 'Thailand', null, 'Nong Muang Khai', '12140');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (62, 'Serbia', null, 'Bojnik', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (63, 'Ukraine', null, 'Varva', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (64, 'Mexico', 'Oaxaca', 'Las Flores', '70317');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (65, 'Russia', null, 'Shcherbinka', '142720');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (66, 'Philippines', null, 'Lila', '6304');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (67, 'United States', 'Indiana', 'Terre Haute', '47812');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (68, 'Russia', null, 'Boksitogorsk', '187642');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (69, 'Philippines', null, 'Matala', '1105');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (70, 'Philippines', null, 'Cabatang', '5508');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (71, 'China', null, 'Tujing', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (72, 'China', null, 'Xietang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (73, 'France', 'Centre', 'Blois', '41904 CEDEX 9');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (74, 'China', null, 'Xinji', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (75, 'France', 'Île-de-France', 'Courtaboeuf', '91948 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (76, 'Portugal', 'Braga', 'Nine', '4775-446');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (77, 'Russia', null, 'Novokuybyshevsk', '446209');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (78, 'Philippines', null, 'Dahay', '9512');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (79, 'China', null, 'Tongyuanpu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (80, 'Vietnam', null, 'Ea T’ling', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (81, 'China', null, 'Longgang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (82, 'Philippines', null, 'Limbalod', '9407');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (83, 'Portugal', 'Viseu', 'Outeiro', '4690-282');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (84, 'China', null, 'Tianbao', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (85, 'Indonesia', null, 'Banjar Pangkungtibah Selatan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (86, 'Mongolia', null, 'Tsengel', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (87, 'Indonesia', null, 'Situbondo', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (88, 'Pakistan', null, 'Nārang', '39051');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (89, 'Nigeria', null, 'Oguma', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (90, 'Palestinian Territory', null, 'Bayt ‘Anān', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (91, 'Canada', 'Prince Edward Island', 'Cornwall', 'L4E');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (92, 'Philippines', null, 'Paraiso', '1104');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (93, 'Czech Republic', null, 'Koryčany', '768 05');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (94, 'Indonesia', null, 'Wanasari Baleran', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (95, 'Argentina', null, 'Brandsen', '1981');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (96, 'China', null, 'Qingchuan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (97, 'China', null, 'Hangchuan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (98, 'China', null, 'Maying', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (99, 'Thailand', null, 'Tha Muang', '71110');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (100, 'Libya', null, 'Hūn', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (101, 'Japan', null, 'Okunoya', '314-0116');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (102, 'Ukraine', null, 'Navariya', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (103, 'Palestinian Territory', null, 'Iktābah', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (104, 'Philippines', null, 'Uacon', '1169');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (105, 'Indonesia', null, 'Tanarara', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (106, 'Mongolia', null, 'Dzüünbulag', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (107, 'Benin', null, 'Savalou', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (108, 'Russia', null, 'Novospasskoye', '607914');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (109, 'Kazakhstan', null, 'Aqtaū', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (110, 'Greece', null, 'Pyrgetós', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (111, 'Iraq', null, 'Mosul', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (112, 'Sweden', 'Jönköping', 'Eksjö', '575 35');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (113, 'Portugal', 'Braga', 'Gondar', '4835-541');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (114, 'China', null, 'Lincheng', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (115, 'China', null, 'Baishui', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (116, 'United States', 'California', 'Mountain View', '94042');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (117, 'Indonesia', null, 'Sembakung', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (118, 'Malawi', null, 'Machinga', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (119, 'Syria', null, 'Ḩarf al Musaytirah', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (120, 'France', 'Île-de-France', 'Saint-Quentin-en-Yvelines', '78181 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (121, 'Portugal', 'Viseu', 'Beselga', '3630-058');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (122, 'Canada', 'Québec', 'Waterloo', 'V9J');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (123, 'China', null, 'Sanligang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (124, 'Russia', null, 'Garbolovo', '188668');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (125, 'United States', 'Louisiana', 'Monroe', '71213');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (126, 'Morocco', null, 'Larache', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (127, 'Chile', null, 'Melipilla', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (128, 'Russia', null, 'Babushkin', '671235');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (129, 'China', null, 'Sunfang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (130, 'Luxembourg', null, 'Esch-sur-Alzette', 'L-4354');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (131, 'China', null, 'Zhenghu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (132, 'Philippines', null, 'Lingion', '8708');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (133, 'Russia', null, 'Ferapontovo', '161120');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (134, 'Indonesia', null, 'Karangsembung', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (135, 'United States', 'Texas', 'Conroe', '77305');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (136, 'Malaysia', 'Sarawak', 'Kuching', '93612');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (137, 'China', null, 'Gufeng', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (138, 'Poland', null, 'Skarżysko-Kamienna', '26-113');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (139, 'China', null, 'Dingshan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (140, 'France', 'Champagne-Ardenne', 'Reims', '51074 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (141, 'Philippines', null, 'Tobias Fornier', '5716');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (142, 'Brazil', null, 'Tupaciguara', '38430-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (143, 'Armenia', null, 'Fantan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (144, 'Philippines', null, 'Bairan', '4511');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (145, 'Russia', null, 'Volgograd', '309621');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (146, 'China', null, 'Shuanglongchang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (147, 'Thailand', null, 'Thap Khlo', '71000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (148, 'Indonesia', null, 'Ngurensiti', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (149, 'Vietnam', null, 'Quận Năm', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (150, 'China', null, 'Dungang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (151, 'Czech Republic', null, 'Drásov', '664 24');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (152, 'China', null, 'Nierumai', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (153, 'China', null, 'Guotan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (154, 'Portugal', 'Santarém', 'Porto Alto', '2135-027');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (155, 'Sweden', 'Uppsala', 'Uppsala', '753 26');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (156, 'Brazil', null, 'Ipueiras', '77553-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (157, 'Netherlands', 'Provincie Zuid-Holland', 'Rijswijk', '2284');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (158, 'Philippines', null, 'Guijalo', '7113');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (159, 'Ukraine', null, 'Berezivka', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (160, 'China', null, 'Tajike’abati', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (161, 'Jordan', null, 'Mafraq', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (162, 'China', null, 'Nanqiao', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (163, 'Peru', null, 'La Oroya', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (164, 'Denmark', 'Region Hovedstaden', 'København', '1098');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (165, 'France', 'Rhône-Alpes', 'Saint-Chamond', '42404 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (166, 'Indonesia', null, 'Daja', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (167, 'Portugal', 'Aveiro', 'Santa Maria da Feira', '4520-162');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (168, 'Russia', null, 'Olenegorsk', '646400');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (169, 'China', null, 'Damiku', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (170, 'Russia', null, 'Planovskoye', '361222');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (171, 'Australia', 'New South Wales', 'Sydney', '1033');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (172, 'France', 'Île-de-France', 'Bondoufle', '91077 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (173, 'Poland', null, 'Czarna', '39-215');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (174, 'Costa Rica', null, 'Cañas', '50601');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (175, 'Maldives', null, 'Open Stage', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (176, 'Japan', null, 'Kawaguchi', '999-5203');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (177, 'Macedonia', null, 'Oslomej', '6254');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (178, 'China', null, 'Meishan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (179, 'Indonesia', null, 'Weetombo', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (180, 'Russia', null, 'Kraskino', '692715');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (181, 'Uzbekistan', null, 'Qarshi', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (182, 'Germany', 'Hessen', 'Frankfurt am Main', '60549');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (183, 'Nigeria', null, 'Gumel', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (184, 'Tunisia', null, 'Tozeur', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (185, 'Ukraine', null, 'Nuyno', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (186, 'Czech Republic', null, 'Příbor', '742 58');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (187, 'Sweden', 'Stockholm', 'Stockholm', '120 16');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (188, 'Cuba', null, 'Cárdenas', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (189, 'Jordan', null, 'Ma''an', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (190, 'China', null, 'Hanchang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (191, 'Seychelles', null, 'Port Glaud', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (192, 'Honduras', null, 'Monjarás', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (193, 'France', 'Rhône-Alpes', 'Eybens', '38327 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (194, 'Myanmar', null, 'Kyaikto', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (195, 'Nigeria', null, 'Illela', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (196, 'China', null, 'Xiaotang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (197, 'China', null, 'Yaxi', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (198, 'Palestinian Territory', null, 'Wādī as Salqā', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (199, 'Honduras', null, 'La Guacamaya', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (200, 'Ukraine', null, 'Chernivtsi', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (201, 'China', null, 'Jiangzhang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (202, 'Philippines', null, 'Dinahican', '0850');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (203, 'Brazil', null, 'São Paulo', '01000-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (204, 'Ukraine', null, 'Prosyana', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (205, 'Ukraine', null, 'Tayirove', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (206, 'Syria', null, 'Sarmīn', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (207, 'Portugal', 'Braga', 'Eirado', '4730-510');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (208, 'Botswana', null, 'Kanye', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (209, 'South Africa', null, 'Driefontein', '4142');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (210, 'Qatar', null, 'Ar Ru’ays', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (211, 'Ethiopia', null, 'Guder', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (212, 'South Africa', null, 'Himeville', '3652');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (213, 'France', 'Île-de-France', 'Créteil', '94009 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (214, 'China', null, 'Changqing', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (215, 'Indonesia', null, 'Mujur', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (216, 'Portugal', 'Portalegre', 'Vale Maceiras', '7460-204');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (217, 'United Kingdom', 'England', 'Whitchurch', 'BS14');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (218, 'Russia', null, 'Chernyanka', '309573');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (219, 'Russia', null, 'Mariinsk', '652156');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (220, 'France', 'Languedoc-Roussillon', 'Perpignan', '66019 CEDEX 9');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (221, 'United States', 'Oklahoma', 'Oklahoma City', '73119');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (222, 'China', null, 'Tongzhong', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (223, 'China', null, 'Tangzi', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (224, 'Yemen', null, 'Sa''dah', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (225, 'China', null, 'Changyuan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (226, 'China', null, 'Aba', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (227, 'Kazakhstan', null, 'Borovskoy', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (228, 'Thailand', null, 'Phetchaburi', '76150');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (229, 'Sweden', 'Stockholm', 'Ingarö', '134 61');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (230, 'Norway', 'Vest-Agder', 'Kristiansand S', '4695');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (231, 'Poland', null, 'Wąbrzeźno', '87-201');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (232, 'Portugal', 'Beja', 'Odivelas', '7900-374');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (233, 'Venezuela', null, 'Palmasola', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (234, 'Philippines', null, 'Malalag', '8010');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (235, 'Taiwan', null, 'Jincheng', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (236, 'Portugal', 'Viseu', 'Vila Nova', '4690-588');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (237, 'China', null, 'Jingping', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (238, 'Czech Republic', null, 'Kunčice pod Ondřejníkem', '739 13');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (239, 'Russia', null, 'Bogoroditsk', '301839');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (240, 'United States', 'Arkansas', 'Little Rock', '72215');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (241, 'El Salvador', null, 'Nueva Guadalupe', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (242, 'Sweden', 'Stockholm', 'Kista', '164 40');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (243, 'Indonesia', null, 'Pecatu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (244, 'China', null, 'Liushutun', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (245, 'China', null, 'Liwu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (246, 'China', null, 'Lingyang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (247, 'Kuwait', null, 'Ḩawallī', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (248, 'China', null, 'Anwen', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (249, 'Philippines', null, 'Tuka', '3120');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (250, 'Angola', null, 'Caluquembe', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (251, 'Thailand', null, 'Phonphisai', '43120');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (252, 'China', null, 'Anlu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (253, 'Poland', null, 'Jabłonica Polska', '38-421');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (254, 'Guinea-Bissau', null, 'Quebo', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (255, 'Indonesia', null, 'Gesikan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (256, 'Ukraine', null, 'Zalesnoye', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (257, 'Czech Republic', null, 'Dvůr Králové nad Labem', '544 01');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (258, 'Nigeria', null, 'Ochobo', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (259, 'Japan', null, 'Takefu', '919-0201');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (260, 'Sweden', 'Stockholm', 'Södertälje', '151 44');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (261, 'China', null, 'Anfu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (262, 'Switzerland', 'Kanton Zürich', 'Winterthur', '8411');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (263, 'Oman', null, 'Nizwá', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (264, 'Cameroon', null, 'Bertoua', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (265, 'Nepal', null, 'Tīkāpur', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (266, 'China', null, 'Koktokay', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (267, 'China', null, 'Yajin', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (268, 'Indonesia', null, 'Manola', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (269, 'Ireland', null, 'Fairview', 'D17');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (270, 'Peru', null, 'Corani', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (271, 'Macedonia', null, 'Крива Паланка', '1333');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (272, 'China', null, 'Luoyang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (273, 'Indonesia', null, 'Sorongan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (274, 'China', null, 'Denglong', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (275, 'Italy', 'Toscana', 'Firenze', '50124');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (276, 'Brazil', null, 'Guanambi', '46430-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (277, 'Nigeria', null, 'Uba', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (278, 'Namibia', null, 'Katima Mulilo', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (279, 'Indonesia', null, 'Pacar', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (280, 'Uruguay', null, 'Soca', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (281, 'France', 'Provence-Alpes-Côte d''Azur', 'Marseille', '13293 CEDEX 08');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (282, 'Zambia', null, 'Kasama', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (283, 'Poland', null, 'Zakliczyn', '32-840');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (284, 'Poland', null, 'Świecie nad Osą', '28-425');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (285, 'China', null, 'Yinzhu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (286, 'Philippines', null, 'Bulo', '2510');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (287, 'Indonesia', null, 'Sidomekar', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (288, 'Namibia', null, 'Nkurenkuru', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (289, 'Sweden', 'Stockholm', 'Södertälje', '151 22');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (290, 'Vietnam', null, 'Uyen Hung', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (291, 'Canada', 'Saskatchewan', 'Lumsden', 'L7E');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (292, 'China', null, 'Huangdao', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (293, 'Latvia', null, 'Ādaži', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (294, 'Philippines', null, 'Cateel', '9220');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (295, 'Malaysia', 'Terengganu', 'Kuala Terengganu', '20551');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (296, 'Russia', null, 'Bisert’', '623050');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (297, 'China', null, 'Longtian', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (298, 'Tanzania', null, 'Mingoyo', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (299, 'China', null, 'Dongguang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (300, 'Iran', null, 'Nīshābūr', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (301, 'China', null, 'Ruixi', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (302, 'Thailand', null, 'Khlong Sam Wa', '10240');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (303, 'China', null, 'Yunzhong', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (304, 'Sweden', 'Stockholm', 'Åkersberga', '184 23');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (305, 'Brazil', null, 'Porecatu', '86160-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (306, 'Russia', null, 'Gorskaya', '197755');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (307, 'Ukraine', null, 'Krasnohrad', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (308, 'Madagascar', null, 'Fianarantsoa', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (309, 'Indonesia', null, 'Naebugis', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (310, 'Indonesia', null, 'Sampit', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (311, 'Honduras', null, 'Silca', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (312, 'China', null, 'Shuangmiao', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (313, 'Brazil', null, 'Extremoz', '59575-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (314, 'Peru', null, 'Canis', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (315, 'Malawi', null, 'Blantyre', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (316, 'Honduras', null, 'El Lolo', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (317, 'Japan', null, 'Sunagawa', '997-0415');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (318, 'Iran', null, 'Ābdānān', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (319, 'Argentina', null, 'El Quebrachal', '5101');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (320, 'Iran', null, 'Borāzjān', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (321, 'Philippines', null, 'Bularit', '2302');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (322, 'Afghanistan', null, 'Būrkah', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (323, 'Bulgaria', null, 'Slavyanovo', '5840');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (324, 'Portugal', 'Porto', 'Boucinhas', '4650-805');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (325, 'Australia', 'South Australia', 'Adelaide Mail Centre', '5899');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (326, 'China', null, 'Shanyang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (327, 'Philippines', null, 'Cabog', '1101');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (328, 'China', null, 'Xiangcunxiang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (329, 'China', null, 'Hekou', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (330, 'United States', 'Arizona', 'Phoenix', '85072');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (331, 'Philippines', null, 'Talavera', '3114');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (332, 'Armenia', null, 'Ejmiatsin', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (333, 'Indonesia', null, 'Timbulsari', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (334, 'China', null, 'Beicheng', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (335, 'Japan', null, 'Hino', '919-0222');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (336, 'Indonesia', null, 'Batang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (337, 'Portugal', 'Porto', 'Escola', '4600-730');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (338, 'Portugal', 'Santarém', 'Cortiçóis', '2080-381');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (339, 'France', 'Midi-Pyrénées', 'Toulouse', '31019 CEDEX 2');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (340, 'Russia', null, 'Novoaleksandrovsk', '356003');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (341, 'Canada', 'Ontario', 'St. Catharines', 'L2P');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (342, 'Croatia', null, 'Gospić', '53000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (343, 'Ethiopia', null, 'Ginir', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (344, 'Australia', 'South Australia', 'Adelaide Mail Centre', '5869');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (345, 'Poland', null, 'Kolsko', '67-415');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (346, 'China', null, 'Guancheng', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (347, 'Ukraine', null, 'Snizhne', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (348, 'France', 'Languedoc-Roussillon', 'Perpignan', '66921 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (349, 'Nigeria', null, 'Suya', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (350, 'Poland', null, 'Zalewo', '14-230');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (351, 'Kazakhstan', null, 'Lisakovsk', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (352, 'China', null, 'Nancha', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (353, 'Belarus', null, 'Chavusy', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (354, 'Palestinian Territory', null, 'Mardā', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (355, 'Palestinian Territory', null, 'Al Mughayyir', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (356, 'China', null, 'Tucheng', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (357, 'Portugal', 'Porto', 'Oliveiras', '4745-235');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (358, 'Canada', 'Alberta', 'Killam', 'A0A');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (359, 'Azerbaijan', null, 'Maştağa', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (360, 'China', null, 'Changle', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (361, 'Mexico', 'Veracruz Llave', 'Ricardo Flores Magon', '93650');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (362, 'Indonesia', null, 'Bluri', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (363, 'Thailand', null, 'Phitsanulok', '65000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (364, 'China', null, 'Shaochang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (365, 'Czech Republic', null, 'Mukařov', '411 45');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (366, 'France', 'Auvergne', 'Clermont-Ferrand', '63009 CEDEX 1');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (367, 'South Korea', null, 'Changnyeong', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (368, 'China', null, 'Hangzhou', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (369, 'Russia', null, 'Chashnikovo', '143912');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (370, 'Indonesia', null, 'Samangawah', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (371, 'France', 'Provence-Alpes-Côte d''Azur', 'La Seyne-sur-Mer', '83514 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (372, 'China', null, 'Dasha', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (373, 'Tunisia', null, 'Zaghouan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (374, 'France', 'Rhône-Alpes', 'Firminy', '42704 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (375, 'Indonesia', null, 'Sambong', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (376, 'Peru', null, 'Alis', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (377, 'Poland', null, 'Lipka', '77-420');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (378, 'Russia', null, 'Linëvo', '633216');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (379, 'China', null, 'Jiapeng', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (380, 'Japan', null, 'Shiki', '863-2503');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (381, 'China', null, 'Pinghu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (382, 'Portugal', 'Faro', 'São Brás de Alportel', '8150-105');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (383, 'Czech Republic', null, 'Lípa', '763 11');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (384, 'China', null, 'Zhuli', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (385, 'Portugal', 'Braga', 'Gondomar', '4800-198');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (386, 'Jordan', null, 'As Salţ', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (387, 'Portugal', 'Coimbra', 'Corujeira', '3070-106');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (388, 'Panama', null, 'Panamá', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (389, 'Indonesia', null, 'Gabahan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (390, 'Kazakhstan', null, 'Shardara', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (391, 'China', null, 'Guifeng', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (392, 'Mauritius', null, 'Flic en Flac', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (393, 'Russia', null, 'Shedok', '352560');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (394, 'Philippines', null, 'Tarragona', '8201');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (395, 'Tanzania', null, 'Mabamba', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (396, 'Colombia', null, 'San Carlos', '232517');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (397, 'Russia', null, 'Staronizhestebliyevskaya', '606231');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (398, 'Philippines', null, 'Balud', '5412');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (399, 'Croatia', null, 'Gvozd', '44410');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (400, 'Brazil', null, 'Santa Helena', '89915-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (401, 'Portugal', 'Lisboa', 'Linhó', '2710-144');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (402, 'Indonesia', null, 'Redakodi', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (403, 'Bosnia and Herzegovina', null, 'Donji Vakuf', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (404, 'China', null, 'Jiefu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (405, 'Democratic Republic of the Congo', null, 'Goma', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (406, 'Indonesia', null, 'Garisul', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (407, 'Indonesia', null, 'Karangparwa', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (408, 'China', null, 'Zhongfan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (409, 'Russia', null, 'Svetlyy Yar', '404170');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (410, 'China', null, 'Shuangcheng', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (411, 'Germany', 'Hessen', 'Wetzlar', '35581');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (412, 'Czech Republic', null, 'Nové Strašecí', '271 01');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (413, 'Nigeria', null, 'Lafiagi', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (414, 'Mexico', 'Guerrero', 'San Rafael', '41640');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (415, 'China', null, 'Wenping', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (416, 'Belarus', null, 'Aktsyabrski', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (417, 'Thailand', null, 'Nong Don', '50320');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (418, 'Sweden', 'Dalarna', 'Säter', '783 35');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (419, 'Philippines', null, 'Santo Domingo', '4508');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (420, 'United States', 'Kansas', 'Kansas City', '66105');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (421, 'Brazil', null, 'Salvador', '40000-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (422, 'China', null, 'Changping', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (423, 'Portugal', 'Évora', 'Alqueva', '7220-043');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (424, 'China', null, 'Wushan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (425, 'Lebanon', null, 'Jbaïl', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (426, 'Indonesia', null, 'Fatumuti', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (427, 'Togo', null, 'Bassar', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (428, 'Jordan', null, 'Qīr Moāv', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (429, 'Peru', null, 'Urasqui', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (430, 'China', null, 'Xiaruyue', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (431, 'China', null, 'Jiajiaying', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (432, 'Bulgaria', null, 'Dimitrovgrad', '6435');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (433, 'Czech Republic', null, 'Ústí nad Orlicí', '562 06');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (434, 'Ukraine', null, 'Kremenets’', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (435, 'Colombia', null, 'La Jagua de Ibirico', '203027');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (436, 'Indonesia', null, 'Rancabugel', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (437, 'China', null, 'Fenchen', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (438, 'Azerbaijan', null, 'Bakıxanov', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (439, 'Uganda', null, 'Margherita', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (440, 'Indonesia', null, 'Kutamangu', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (441, 'Malaysia', 'Kuala Lumpur', 'Kuala Lumpur', '57990');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (442, 'Norway', 'Oslo', 'Oslo', '0194');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (443, 'Argentina', null, 'General Pinedo', '3732');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (444, 'Yemen', null, 'Aş Şalw', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (445, 'Brazil', null, 'Abreu e Lima', '53500-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (446, 'Peru', null, 'Tomas', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (447, 'Croatia', null, 'Koška', '31224');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (448, 'China', null, 'Bachuan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (449, 'Ivory Coast', null, 'Soubré', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (450, 'Morocco', null, 'Tamorot', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (451, 'Greece', null, 'Plomárion', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (452, 'France', 'Provence-Alpes-Côte d''Azur', 'Le Cannet', '06116 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (453, 'Thailand', null, 'Mae Sai', '57130');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (454, 'Russia', null, 'Bol’shaya Setun’', '249028');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (455, 'China', null, 'Shihui', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (456, 'Philippines', null, 'Baloc', '3114');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (457, 'Macedonia', null, 'Kumanovo', '1300');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (458, 'Canada', 'British Columbia', 'Ucluelet', 'G6E');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (459, 'China', null, 'Yong’an', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (460, 'Croatia', null, 'Mačkovec', '40000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (461, 'Poland', null, 'Skoroszyce', '48-320');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (462, 'Indonesia', null, 'Baluk', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (463, 'Poland', null, 'Bobowa', '38-350');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (464, 'Philippines', null, 'Sison', '8404');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (465, 'Iran', null, 'Mākū', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (466, 'Luxembourg', null, 'Bergem', 'L-3318');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (467, 'Indonesia', null, 'Long Beluah', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (468, 'Malawi', null, 'Mchinji', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (469, 'Russia', null, 'Svetlyy', '238548');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (470, 'Ecuador', null, 'Machachi', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (471, 'Argentina', null, 'Río Gallegos', '9400');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (472, 'Uruguay', null, 'Quebracho', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (473, 'China', null, 'Jiezi', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (474, 'China', null, 'Jiangzhou', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (475, 'Bolivia', null, 'Arani', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (476, 'China', null, 'Xinjia', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (477, 'Indonesia', null, 'Ciherang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (478, 'Philippines', null, 'Matabao', '8601');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (479, 'Finland', null, 'Siikajoki', '92320');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (480, 'Czech Republic', null, 'Sobotka', '507 43');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (481, 'China', null, 'Pulian', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (482, 'Poland', null, 'Nieszawa', '87-730');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (483, 'China', null, 'Xike', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (484, 'Iraq', null, 'Nāḩīyat Saddat al Hindīyah', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (485, 'France', 'Provence-Alpes-Côte d''Azur', 'Draguignan', '83300');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (486, 'Indonesia', null, 'Siwalan', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (487, 'Brazil', null, 'Barueri', '06400-000');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (488, 'China', null, 'Garang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (489, 'South Africa', null, 'Calvinia', '8193');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (490, 'Czech Republic', null, 'Dobratice', '739 51');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (491, 'France', 'Île-de-France', 'Bonneuil-sur-Marne', '94384 CEDEX');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (492, 'Russia', null, 'Severnyy', '309060');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (493, 'Philippines', null, 'Cartagena', '2432');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (494, 'China', null, 'Yangce', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (495, 'Cameroon', null, 'Foumban', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (496, 'Russia', null, 'Vsevolozhsk', '188649');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (497, 'China', null, 'Wenchang', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (498, 'Serbia', null, 'Klek', null);
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (499, 'Russia', null, 'Muromtsevo', '601389');
insert into LOCATION (LocationID, Country, State, City, Zipcode) values (500, 'Russia', null, 'Novikovo', '659518');
